services:
  # Backend API
  - type: web
    name: albilad-voice-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LABIBA_BASE_URL
        value: https://chat.labibabot.com
      - key: LABIBA_SESSION_ID
        sync: false
      - key: LABIBA_STORY_ID
        sync: false
      - key: OPENAI_STT_MODEL
        value: gpt-4o-transcribe

  # Frontend
  - type: web
    name: albilad-voice-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: albilad-voice-backend
          envVarKey: RENDER_EXTERNAL_URL
